### ISSUE TITLE
cannot find module @/auth

### ISSUE THREAD

**Issue by antonind72** [omermecitoglu/example-user-service#1]
Hello, I tried to use your module because I thought it would go well with my nextjs api, but I encounter an error:

⨯ Error: Cannot find module '@/auth'
Require stack:
- C:\Users\nordi\Desktop\newproj\batisi\.next\server\vendor-chunks\@omer-x.js
    at async DocsApiPage (admin/docs/api/page.tsx:14:18)
    
    
 is the library compatible if we use next-auth@beta?
or is this another reason why I'm getting this error

**Comment by omermecitoglu** [comment]
In my [next-openapi-json-generator](https://github.com/omermecitoglu/next-openapi-json-generator) module, I need to delete all the irrelevant imports [as you can see here](https://github.com/omermecitoglu/next-openapi-json-generator/blob/b9a6faf2e672114fb8bf9d1a4f228653aa5406b5/src/core/transpile.ts#L4). So I think `@/auth` was ignored by that regexp somehow. I'll do some tests and get back to you asap.

**Comment by omermecitoglu** [comment]
```
npm i @omer-x/next-openapi-json-generator@0.2.5
```
this will fix your problem

**Comment by antonind72** [comment]
Thanks for your help and resolving the issue quickly!
