### ISSUE TITLE
I want you to make a type without using drizzle

### ISSUE THREAD

**Issue by mineclover** [omermecitoglu/example-user-service#10]
I don't use drizzle
Failed to create document without drizzle

I want you to add an example
thank!!!!

**Comment by omermecitoglu** [comment]
What kind of example do you need? If you are trying it with TypeORM. I think it doesn't work well with nextjs. That was the reason why I switched to drizzle. I think there are not many ORM options for typescript and nextjs. Prisma and drizzle are just two of them that I know works well.

**Comment by BangJunwoo** [comment]
> 어떤 종류의 예가 필요하세요? TypeORM으로 시도한다면요. nextjs에서는 잘 작동하지 않는 것 같아요. 그게 제가 drizzle로 바꾼 이유예요. 타입스크립트와 nextjs에 대한 ORM 옵션이 많지 않은 것 같아요. Prisma와 drizzle은 제가 잘 작동하는 것으로 알고 있는 두 가지에 불과해요.

I am looking for a form that is easy to use for nextjs while making openapi specifications purely with zod and next

**Comment by mineclover** [comment]
> What kind of example do you need? If you are trying it with TypeORM. I think it doesn't work well with nextjs. That was the reason why I switched to drizzle. I think there are not many ORM options for typescript and nextjs. Prisma and drizzle are just two of them that I know works well.

I am looking for a form that is easy to use for nextjs while making openapi specifications purely with zod and next

**Comment by omermecitoglu** [comment]
Ok you can find the example without drizzle in [`without-drizzle`](https://github.com/omermecitoglu/example-user-service/tree/without-drizzle) branch
